import type {
  ApprovalItem,
  InspectionRecord,
  LandlordDocument,
  LandlordNotification,
  LandlordProperty,
  MaintenanceJob,
  MessageThread,
  MonthlyStatement,
  OutstandingAmount,
  PaymentRecord,
  ThreadMessage,
} from './types';

export const PROPERTIES: LandlordProperty[] = [
  {
    id: 'prop-1',
    address: '12 Ocean View Pde',
    suburb: 'Miami',
    tenantName: 'Sarah Chen',
    rentWeekly: 720,
    status: 'occupied',
    needAction: true,
    bedrooms: 3,
    bathrooms: 2,
    parkingSpaces: 2,
    leaseStart: '2024-08-01',
    leaseEnd: '2026-07-31',
    agencyName: 'CROSSUB Property Management',
    propertyManager: 'Marcus Reid',
    managerEmail: 'marcus@crossub.com.au',
    managerPhone: '+61 7 5555 0100',
  },
  {
    id: 'prop-2',
    address: '4/88 Surf Rd',
    suburb: 'Broadbeach',
    tenantName: 'James & Emma Walsh',
    rentWeekly: 650,
    status: 'vacating',
    needAction: true,
    bedrooms: 2,
    bathrooms: 1,
    parkingSpaces: 1,
    leaseStart: '2024-06-01',
    leaseEnd: '2026-06-07',
    agencyName: 'CROSSUB Property Management',
    propertyManager: 'Marcus Reid',
    managerEmail: 'marcus@crossub.com.au',
    managerPhone: '+61 7 5555 0100',
  },
  {
    id: 'prop-3',
    address: '7 Palm Court',
    suburb: 'Burleigh Heads',
    tenantName: 'Vacant',
    rentWeekly: 0,
    status: 'vacant',
    needAction: false,
    bedrooms: 2,
    bathrooms: 2,
    parkingSpaces: 1,
    agencyName: 'CROSSUB Property Management',
    propertyManager: 'Lisa Nguyen',
    managerEmail: 'lisa@crossub.com.au',
    managerPhone: '+61 7 5555 0101',
  },
];

export const APPROVALS: ApprovalItem[] = [
  {
    id: 'apr-1',
    category: 'maintenance',
    title: 'Hot water system repair quote',
    description:
      'Licensed plumber quote for HWS leak. Tenant reported pooling water. Recommend approval — only option available this week.',
    propertyId: 'prop-1',
    propertyAddress: '12 Ocean View Pde, Miami',
    amount: 1840,
    requestedBy: 'Marcus Reid (Property Manager)',
    requestedAt: '2026-05-25T08:00:00',
    status: 'pending',
    priority: 'urgent',
    recommendation: 'Approve — urgent repair to prevent further water damage.',
    documents: [{ name: 'Quote — Gold Coast Plumbing.pdf', url: '#' }],
  },
  {
    id: 'apr-2',
    category: 'rent_review',
    title: 'Rent increase recommendation',
    description:
      'Market analysis supports increase from $720 to $750 per week at lease renewal.',
    propertyId: 'prop-1',
    propertyAddress: '12 Ocean View Pde, Miami',
    amount: 30,
    requestedBy: 'Marcus Reid (Property Manager)',
    requestedAt: '2026-05-20T10:00:00',
    status: 'pending',
    priority: 'normal',
    recommendation: 'Comparable properties in Miami are leasing at $740–$780/week.',
  },
  {
    id: 'apr-3',
    category: 'lease_renewal',
    title: 'Lease renewal — 12 months',
    description: 'Tenant Sarah Chen wishes to renew for 12 months at proposed new rent.',
    propertyId: 'prop-1',
    propertyAddress: '12 Ocean View Pde, Miami',
    requestedBy: 'Marcus Reid (Property Manager)',
    requestedAt: '2026-05-18T14:00:00',
    status: 'pending',
    priority: 'normal',
  },
  {
    id: 'apr-4',
    category: 'special_expense',
    title: 'Emergency locksmith call-out',
    description: 'Tenant locked out after hours. Locksmith fee to be recovered from tenant bond if applicable.',
    propertyId: 'prop-2',
    propertyAddress: '4/88 Surf Rd, Broadbeach',
    amount: 285,
    requestedBy: 'Lisa Nguyen (Property Manager)',
    requestedAt: '2026-05-22T19:30:00',
    status: 'pending',
    priority: 'normal',
  },
  {
    id: 'apr-5',
    category: 'ingoing_inspection',
    title: 'Ingoing inspection dispute',
    description: 'Tenant disputes bathroom condition rating. Your approval required to proceed.',
    propertyId: 'prop-2',
    propertyAddress: '4/88 Surf Rd, Broadbeach',
    requestedBy: 'Marcus Reid (Property Manager)',
    requestedAt: '2026-05-15T11:00:00',
    status: 'more_info',
    priority: 'normal',
  },
];

export const INSPECTIONS: InspectionRecord[] = [
  {
    id: 'insp-1',
    type: 'open',
    propertyId: 'prop-3',
    propertyAddress: '7 Palm Court, Burleigh Heads',
    inspectionDate: '2026-05-24T10:00:00',
    inspectorName: 'Lisa Nguyen',
    attendees: 8,
    status: 'completed',
  },
  {
    id: 'insp-2',
    type: 'routine',
    propertyId: 'prop-1',
    propertyAddress: '12 Ocean View Pde, Miami',
    inspectionDate: '2026-05-10T09:30:00',
    inspectorName: 'Marcus Reid',
    status: 'completed',
    issuesIdentified: 1,
    tenantComments: 'Kitchen tap drips occasionally.',
    agentComments: 'Minor maintenance recommended — non-urgent.',
  },
  {
    id: 'insp-3',
    type: 'outgoing',
    propertyId: 'prop-2',
    propertyAddress: '4/88 Surf Rd, Broadbeach',
    inspectionDate: '2026-05-27T10:00:00',
    inspectorName: 'Marcus Reid',
    status: 'scheduled',
    damageSummary: 'Pending inspection',
  },
  {
    id: 'insp-4',
    type: 'ingoing',
    propertyId: 'prop-2',
    propertyAddress: '4/88 Surf Rd, Broadbeach',
    inspectionDate: '2024-06-01T10:00:00',
    inspectorName: 'Marcus Reid',
    status: 'completed',
    tenantComments: 'Bathroom grout discolouration noted.',
  },
];

export const MAINTENANCE: MaintenanceJob[] = [
  {
    id: 'mnt-1',
    propertyId: 'prop-1',
    propertyAddress: '12 Ocean View Pde, Miami',
    issueDescription: 'Hot water system leak',
    priority: 'urgent',
    contractorName: 'Gold Coast Plumbing Co.',
    quotedAmount: 1840,
    status: 'awaiting_approval',
  },
  {
    id: 'mnt-2',
    propertyId: 'prop-2',
    propertyAddress: '4/88 Surf Rd, Broadbeach',
    issueDescription: 'Exit carpet steam clean',
    priority: 'normal',
    contractorName: 'Coast Clean Services',
    quotedAmount: 320,
    status: 'in_progress',
  },
  {
    id: 'mnt-3',
    propertyId: 'prop-1',
    propertyAddress: '12 Ocean View Pde, Miami',
    issueDescription: 'Kitchen tap washer replacement',
    priority: 'normal',
    contractorName: 'Gold Coast Plumbing Co.',
    totalCost: 145,
    status: 'completed',
    completionDate: '2026-04-15',
    invoiceUrl: '#',
  },
];

export const PAYMENTS: PaymentRecord[] = [
  {
    id: 'pay-1',
    propertyId: 'prop-1',
    propertyAddress: '12 Ocean View Pde, Miami',
    paymentDate: '2026-05-01',
    amount: 3120,
    method: 'Direct debit',
  },
  {
    id: 'pay-2',
    propertyId: 'prop-2',
    propertyAddress: '4/88 Surf Rd, Broadbeach',
    paymentDate: '2026-05-01',
    amount: 2817,
    method: 'Direct debit',
  },
  {
    id: 'pay-3',
    propertyId: 'prop-1',
    propertyAddress: '12 Ocean View Pde, Miami',
    paymentDate: '2026-04-01',
    amount: 3120,
    method: 'Direct debit',
  },
];

export const OUTSTANDING: OutstandingAmount[] = [
  {
    id: 'out-1',
    propertyId: 'prop-2',
    propertyAddress: '4/88 Surf Rd, Broadbeach',
    type: 'rent',
    amount: 650,
    dueDate: '2026-05-15',
  },
];

export const STATEMENTS: MonthlyStatement[] = [
  {
    id: 'stmt-1',
    propertyId: 'prop-1',
    propertyAddress: '12 Ocean View Pde, Miami',
    period: 'May 2026',
    rentalIncome: 3120,
    managementFees: 312,
    maintenanceCosts: 145,
    inspectionCosts: 0,
    utilityExpenses: 0,
    otherExpenses: 0,
    netAmount: 2663,
    availableAt: '2026-06-01',
  },
  {
    id: 'stmt-2',
    propertyId: 'prop-2',
    propertyAddress: '4/88 Surf Rd, Broadbeach',
    period: 'May 2026',
    rentalIncome: 2817,
    managementFees: 282,
    maintenanceCosts: 0,
    inspectionCosts: 95,
    utilityExpenses: 180,
    otherExpenses: 0,
    netAmount: 2260,
    availableAt: '2026-06-01',
  },
  {
    id: 'stmt-3',
    propertyId: 'prop-1',
    propertyAddress: '12 Ocean View Pde, Miami',
    period: 'April 2026',
    rentalIncome: 3120,
    managementFees: 312,
    maintenanceCosts: 0,
    inspectionCosts: 0,
    utilityExpenses: 0,
    otherExpenses: 0,
    netAmount: 2808,
    availableAt: '2026-05-01',
  },
];

export const MESSAGE_THREADS: MessageThread[] = [
  {
    id: 'msg-1',
    propertyId: 'prop-1',
    propertyAddress: '12 Ocean View Pde, Miami',
    subject: 'HWS repair update',
    category: 'maintenance',
    participants: ['Marcus Reid', 'CROSSUB Support'],
    lastMessage: 'Quote uploaded — awaiting your approval.',
    lastAt: '2026-05-25T08:00:00',
    unread: 1,
  },
  {
    id: 'msg-2',
    propertyId: 'prop-1',
    propertyAddress: '12 Ocean View Pde, Miami',
    subject: 'May statement available',
    category: 'accounting',
    participants: ['CROSSUB Accounting'],
    lastMessage: 'Your May 2026 statement is ready to download.',
    lastAt: '2026-06-01T09:00:00',
    unread: 0,
  },
  {
    id: 'msg-3',
    subject: 'General enquiry — portfolio review',
    category: 'general',
    participants: ['Marcus Reid'],
    lastMessage: 'Happy to schedule a call to review your portfolio performance.',
    lastAt: '2026-05-18T14:30:00',
    unread: 0,
  },
];

export const THREAD_MESSAGES: Record<string, ThreadMessage[]> = {
  'msg-1': [
    {
      id: 'm1',
      from: 'Marcus Reid',
      body: 'Hi — the tenant reported a hot water leak. We have a plumber quote for $1,840. Please review in the Approval Centre.',
      at: '2026-05-24T14:30:00',
    },
    {
      id: 'm2',
      from: 'You',
      body: 'Thanks Marcus. I will review the quote today.',
      at: '2026-05-24T16:00:00',
    },
    {
      id: 'm3',
      from: 'Marcus Reid',
      body: 'Quote uploaded — awaiting your approval.',
      at: '2026-05-25T08:00:00',
    },
  ],
};

export const DOCUMENTS: LandlordDocument[] = [
  {
    id: 'doc-1',
    name: 'Management Agreement — Thompson Portfolio',
    category: 'management_agreement',
    uploadedAt: '2024-01-15',
    version: 1,
    url: '#',
  },
  {
    id: 'doc-2',
    name: 'Lease Agreement — 12 Ocean View Pde',
    category: 'lease',
    propertyAddress: '12 Ocean View Pde, Miami',
    uploadedAt: '2024-08-01',
    version: 1,
    url: '#',
  },
  {
    id: 'doc-3',
    name: 'Routine Inspection Report — May 2026',
    category: 'inspection',
    propertyAddress: '12 Ocean View Pde, Miami',
    uploadedAt: '2026-05-10',
    version: 1,
    url: '#',
  },
  {
    id: 'doc-4',
    name: 'Plumber Quote — HWS Repair',
    category: 'maintenance_quote',
    propertyAddress: '12 Ocean View Pde, Miami',
    uploadedAt: '2026-05-25',
    version: 1,
    url: '#',
  },
  {
    id: 'doc-5',
    name: 'May 2026 Statement',
    category: 'statement',
    propertyAddress: '12 Ocean View Pde, Miami',
    uploadedAt: '2026-06-01',
    version: 1,
    url: '#',
  },
];

export const NOTIFICATIONS: LandlordNotification[] = [
  {
    id: 'notif-1',
    type: 'approval_required',
    title: 'Maintenance quote needs approval',
    body: 'Hot water system repair — $1,840 at 12 Ocean View Pde',
    href: '/approvals/apr-1',
    read: false,
    createdAt: '2026-05-25T08:00:00',
  },
  {
    id: 'notif-2',
    type: 'rent_review',
    title: 'Rent review approval required',
    body: 'Proposed increase to $750/week at 12 Ocean View Pde',
    href: '/approvals/apr-2',
    read: false,
    createdAt: '2026-05-20T10:00:00',
  },
  {
    id: 'notif-3',
    type: 'rent_received',
    title: 'Rent received',
    body: '$3,120 deposited for 12 Ocean View Pde — May 2026',
    href: '/accounting',
    read: true,
    createdAt: '2026-05-01T12:00:00',
  },
  {
    id: 'notif-4',
    type: 'arrears',
    title: 'Tenant arrears alert',
    body: '$650 outstanding at 4/88 Surf Rd, Broadbeach',
    href: '/accounting',
    read: false,
    createdAt: '2026-05-16T09:00:00',
  },
  {
    id: 'notif-5',
    type: 'statement',
    title: 'Monthly statement available',
    body: 'May 2026 statements ready for download',
    href: '/statements',
    read: false,
    createdAt: '2026-06-01T09:00:00',
  },
  {
    id: 'notif-6',
    type: 'inspection',
    title: 'Routine inspection completed',
    body: '12 Ocean View Pde — 1 minor issue identified',
    href: '/inspections/insp-2',
    read: true,
    createdAt: '2026-05-10T11:00:00',
  },
];
